ETAB
1412	01.10.1983	PROD	HLIQ  HWEF    BHPT 10 
--********************--
7285	01.04.1975	PROD	HLIQ  HWEF    BHPT 10 
--********************--
10307	01.07.2000	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1781	01.08.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1420	01.02.1968	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1427	01.04.1968	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1426	01.10.1968	INJE	HWAT  HWEF    BHPT 280 
--********************--
8682BYJ	01.03.1994	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1678	01.08.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
9409BYJ	01.07.2000	PROD	HLIQ  HWEF    BHPT 10 
9409BYJ	18.06.2013	INJE	HWAT  HWEF    BHPT 500 
--********************--
2805	01.08.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1407	01.10.1983	PROD	HLIQ  HWEF    BHPT 10 
1407	01.06.1988	INJE	HWAT  HWEF    BHPT 320 
--********************--
2812	01.08.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
352NBRy	01.09.1961	PROD	HLIQ  HWEF    BHPT 10 
--********************--
10311	01.07.2000	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1453	01.10.1983	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1436	01.08.1969	INJE	HWAT  HWEF    BHPT 280 
--********************--
1432	01.02.1968	PROD	HLIQ  HWEF    BHPT 10 
1432	01.04.2001	INJE	HWAT  HWEF    BHPT 220 
--********************--
1431	01.03.1968	PROD	HLIQ  HWEF    BHPT 10 
--********************--
7377	01.04.1975	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1418	01.08.1969	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1419	01.08.1968	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1428	01.11.1968	PROD	HLIQ  HWEF    BHPT 10 
--********************--
2792	01.01.2001	PROD	HLIQ  HWEF    BHPT 10 
--********************--
8630BYJ	01.03.1994	PROD	HLIQ  HWEF    BHPT 10 
--********************--
1416	01.10.1968	INJE	HWAT  HWEF    BHPT 290 
--********************--
ENDE
